"""AI-powered analysis layer — uses Groq/Llama to review scanner findings.

Two-pass architecture:
  Pass 1 (regex/AST): fast, offline, free → raw findings
  Pass 2 (this module): LLM reviews findings with file context → verdicts + explanations

Batches findings by file (one API call per file) for efficiency.
Gracefully degrades when no API key or rate-limited.
"""

import json
import os
import sys
import time
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

from vibecheck.models import Finding, Severity

SYSTEM_PROMPT = """\
You are a security analyst reviewing code generated by AI coding tools (Cursor, Copilot, Claude Code, Bolt, Lovable, Replit Agent).

A static scanner flagged potential security issues. Your job: review each finding against the FULL file context and determine if it's a real vulnerability or a false positive.

For EACH finding, provide:
1. **verdict**: "confirmed" (real issue), "false_positive" (safe in context), or "needs_review" (can't determine without more context)
2. **confidence**: 0-100 (how sure you are)
3. **explanation**: 1-2 sentences explaining WHY this is dangerous or WHY it's safe. Write for a developer who might not understand security. Be specific to this code, not generic.
4. **severity**: "critical", "high", "medium", "low", or null (null = agree with scanner's assessment)
5. **fix**: A specific code fix for this exact code. If false_positive, set to null.

Rules:
- Be precise. "This eval() parses trusted config from a local JSON file" is good. "eval is dangerous" is bad.
- Secrets in .env files are EXPECTED — only flag if .env is committed to git or referenced in client code.
- Test files, examples, and documentation often contain fake credentials — consider the file path.
- If a finding is in a comment or string that's clearly documentation, it's a false positive.
- Hardcoded passwords in test fixtures are usually false positives.
- NEXT_PUBLIC_ env vars are intentionally client-exposed in Next.js — only flag if the var name suggests a secret.

Respond with ONLY valid JSON (no markdown, no explanation outside the JSON):
{
  "findings": [
    {
      "index": 0,
      "verdict": "confirmed",
      "confidence": 85,
      "explanation": "This eval() takes unsanitized user input from req.query, allowing arbitrary code execution.",
      "severity": null,
      "fix": "const data = JSON.parse(req.query.input)"
    }
  ]
}"""

# Max file content to send (chars). Truncate intelligently beyond this.
MAX_FILE_CHARS = 8000
# Max findings per file before we split into multiple calls
MAX_FINDINGS_PER_CALL = 15
# Default model
DEFAULT_MODEL = "llama-3.3-70b-versatile"


class AIAnalyzer:
    """Analyzes scanner findings using Groq LLM for context-aware verdicts."""

    def __init__(self, api_key: str = None, model: str = None):
        self.api_key = api_key or os.environ.get("VIBECHECK_API_KEY") or os.environ.get("GROQ_API_KEY")
        self.model = model or DEFAULT_MODEL
        self._client = None

    @property
    def available(self) -> bool:
        return bool(self.api_key)

    def _get_client(self):
        if self._client is None:
            try:
                from groq import Groq
                self._client = Groq(api_key=self.api_key)
            except ImportError:
                raise RuntimeError(
                    "groq package not installed. Run: pip install groq"
                )
        return self._client

    def analyze(self, findings: list[Finding], callback=None) -> list[Finding]:
        """Analyze findings with AI. Returns the same findings with AI fields populated.

        Args:
            findings: List of Finding objects from the regex/AST pass.
            callback: Optional callable(file_path, num_findings) called per file batch.

        Returns:
            The same Finding objects with ai_* fields populated.
        """
        if not self.available:
            return findings

        if not findings:
            return findings

        # Group findings by file
        by_file: dict[str, list[tuple[int, Finding]]] = defaultdict(list)
        for i, f in enumerate(findings):
            by_file[f.file_path].append((i, f))

        # Process files (2 workers — Groq free tier TPM is tight)
        with ThreadPoolExecutor(max_workers=2) as pool:
            futures = {}
            for file_path, indexed_findings in by_file.items():
                fut = pool.submit(
                    self._analyze_file,
                    file_path,
                    indexed_findings,
                )
                futures[fut] = file_path

            for fut in as_completed(futures):
                file_path = futures[fut]
                try:
                    fut.result()
                    if callback:
                        callback(file_path, len(by_file[file_path]))
                except Exception as e:
                    # Don't fail the whole scan if one file's AI analysis fails
                    print(f"  AI analysis failed for {file_path}: {e}", file=sys.stderr)

        return findings

    def _analyze_file(self, file_path: str, indexed_findings: list[tuple[int, Finding]]):
        """Send one API call per file with all its findings."""
        # Read file content for context
        file_content = self._read_file(file_path)

        # Build the user prompt
        prompt = self._build_prompt(file_path, file_content, indexed_findings)

        # Call Groq
        response = self._call_llm(prompt)

        # Parse and apply results
        self._apply_results(response, indexed_findings)

    def _read_file(self, file_path: str) -> str:
        """Read file content, truncating if too large."""
        try:
            content = Path(file_path).read_text(errors="replace")
        except (OSError, PermissionError):
            return "(file not readable)"

        if len(content) <= MAX_FILE_CHARS:
            return content

        # Truncate but keep the parts around findings
        return content[:MAX_FILE_CHARS] + f"\n... (truncated, {len(content)} chars total)"

    def _build_prompt(self, file_path: str, file_content: str,
                      indexed_findings: list[tuple[int, Finding]]) -> str:
        """Build the user prompt with file content and findings."""
        lines = [f"FILE: {file_path}"]
        lines.append("```")
        lines.append(file_content)
        lines.append("```")
        lines.append("")
        lines.append(f"FINDINGS ({len(indexed_findings)} issues flagged by static scanner):")

        for idx, (_, finding) in enumerate(indexed_findings):
            lines.append(
                f"\n{idx}. [{finding.severity.value.upper()}] Line {finding.line}: "
                f"{finding.check_name}"
            )
            lines.append(f"   Message: {finding.message}")
            if finding.snippet:
                snippet = finding.snippet[:120]
                lines.append(f"   Code: {snippet}")
            if finding.fix_hint:
                lines.append(f"   Scanner suggestion: {finding.fix_hint}")

        return "\n".join(lines)

    def _call_llm(self, user_prompt: str, retries: int = 3) -> dict:
        """Call Groq API with retry on rate limit. Returns parsed JSON."""
        client = self._get_client()

        for attempt in range(retries):
            try:
                response = client.chat.completions.create(
                    model=self.model,
                    messages=[
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt},
                    ],
                    temperature=0.2,
                    max_tokens=4096,
                    response_format={"type": "json_object"},
                )
                content = response.choices[0].message.content
                return json.loads(content)
            except Exception as e:
                err_str = str(e)
                if "429" in err_str or "rate_limit" in err_str:
                    wait = (attempt + 1) * 2  # 2s, 4s, 6s
                    time.sleep(wait)
                    continue
                raise

        # Final attempt failed — re-raise
        raise RuntimeError("Rate limit exceeded after retries")

    def _apply_results(self, response: dict, indexed_findings: list[tuple[int, Finding]]):
        """Apply LLM verdicts back to Finding objects."""
        ai_findings = response.get("findings", [])

        # Build lookup by index
        result_map = {}
        for af in ai_findings:
            idx = af.get("index")
            if idx is not None:
                result_map[idx] = af

        for idx, (_, finding) in enumerate(indexed_findings):
            result = result_map.get(idx)
            if not result:
                continue

            finding.ai_verdict = result.get("verdict", "needs_review")
            finding.ai_confidence = result.get("confidence")
            finding.ai_explanation = result.get("explanation")
            finding.ai_fix = result.get("fix")

            severity_adj = result.get("severity")
            if severity_adj and severity_adj != finding.severity.value:
                # Validate it's a real severity
                try:
                    Severity(severity_adj)
                    finding.ai_severity = severity_adj
                except ValueError:
                    pass
