"""Framework detection and project initialization.

Detects the project's tech stack from manifest files and generates
a .vibeignore with smart defaults for the detected frameworks.
"""

import json
from pathlib import Path

# Framework detection rules: (file_to_check, key_to_search, framework_name, category)
_MANIFEST_SIGNALS = {
    "package.json": {
        "dependencies": {
            "next": ("Next.js", "frontend"),
            "react": ("React", "frontend"),
            "vue": ("Vue", "frontend"),
            "svelte": ("Svelte", "frontend"),
            "express": ("Express", "backend"),
            "fastify": ("Fastify", "backend"),
            "hono": ("Hono", "backend"),
            "@supabase/supabase-js": ("Supabase", "database"),
            "firebase": ("Firebase", "database"),
            "@prisma/client": ("Prisma", "database"),
            "drizzle-orm": ("Drizzle", "database"),
            "stripe": ("Stripe", "payments"),
            "next-auth": ("NextAuth", "auth"),
            "@auth/core": ("Auth.js", "auth"),
            "@clerk/nextjs": ("Clerk", "auth"),
        },
        "devDependencies": {
            "prisma": ("Prisma", "database"),
            "tailwindcss": ("Tailwind CSS", "styling"),
        },
    },
}

# File-based signals (no parsing needed)
_FILE_SIGNALS = [
    ("next.config.js", "Next.js", "frontend"),
    ("next.config.ts", "Next.js", "frontend"),
    ("next.config.mjs", "Next.js", "frontend"),
    ("nuxt.config.ts", "Nuxt", "frontend"),
    ("svelte.config.js", "SvelteKit", "frontend"),
    ("astro.config.mjs", "Astro", "frontend"),
    ("vercel.json", "Vercel", "deploy"),
    ("netlify.toml", "Netlify", "deploy"),
    ("firebase.json", "Firebase", "database"),
    ("supabase/config.toml", "Supabase", "database"),
    ("docker-compose.yml", "Docker", "infra"),
    ("docker-compose.yaml", "Docker", "infra"),
    ("Dockerfile", "Docker", "infra"),
    (".env", ".env file", "config"),
    (".env.local", ".env file", "config"),
    ("manage.py", "Django", "backend"),
    ("Cargo.toml", "Rust", "language"),
    ("go.mod", "Go", "language"),
]

# Python-specific from pyproject.toml or requirements.txt
_PYTHON_DEPS = {
    "fastapi": ("FastAPI", "backend"),
    "django": ("Django", "backend"),
    "flask": ("Flask", "backend"),
    "sqlalchemy": ("SQLAlchemy", "database"),
    "prisma": ("Prisma (Python)", "database"),
    "stripe": ("Stripe", "payments"),
    "supabase": ("Supabase", "database"),
}

# Default .vibeignore for all projects
_BASE_IGNORES = [
    "# VibeCheck ignore file",
    "# Generated by: vibecheck init",
    "",
    "# Dependencies",
    "node_modules/",
    ".venv/",
    "venv/",
    "__pycache__/",
    "",
    "# Build output",
    ".next/",
    "dist/",
    "build/",
    ".output/",
    "target/",
    "",
    "# Package lock files",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "poetry.lock",
    "",
    "# IDE & OS",
    ".idea/",
    ".vscode/",
    ".DS_Store",
    "",
    "# Test fixtures (intentional vulnerable code)",
    "tests/fixtures/",
    "test/fixtures/",
    "__tests__/fixtures/",
    "",
    "# Generated / vendored",
    "*.min.js",
    "*.bundle.js",
    "vendor/",
]

# Framework-specific ignores
_FRAMEWORK_IGNORES = {
    "Next.js": [
        "",
        "# Next.js",
        ".next/",
        ".vercel/",
    ],
    "Nuxt": [
        "",
        "# Nuxt",
        ".nuxt/",
        ".output/",
    ],
    "Django": [
        "",
        "# Django",
        "staticfiles/",
        "media/",
    ],
    "Docker": [
        "",
        "# Docker",
        "*.tar",
    ],
    "Rust": [
        "",
        "# Rust",
        "target/",
    ],
}


def detect_stack(root: Path) -> list[tuple[str, str]]:
    """Detect frameworks and tools in the project.

    Returns list of (framework_name, category) tuples.
    """
    detected = []
    seen = set()

    def _add(name, category):
        if name not in seen:
            seen.add(name)
            detected.append((name, category))

    # Check file-based signals
    for rel_path, name, category in _FILE_SIGNALS:
        if (root / rel_path).exists():
            _add(name, category)

    # Parse package.json
    pkg_path = root / "package.json"
    if pkg_path.exists():
        _add("Node.js", "language")
        try:
            pkg = json.loads(pkg_path.read_text())
            for section_key, dep_map in _MANIFEST_SIGNALS["package.json"].items():
                section = pkg.get(section_key, {})
                for dep_name, (fw_name, fw_cat) in dep_map.items():
                    if dep_name in section:
                        _add(fw_name, fw_cat)
        except (json.JSONDecodeError, OSError):
            pass

    # Parse pyproject.toml (lightweight — just string search, no toml parser needed)
    pyproject = root / "pyproject.toml"
    if pyproject.exists():
        _add("Python", "language")
        try:
            content = pyproject.read_text().lower()
            for dep, (name, cat) in _PYTHON_DEPS.items():
                if dep in content:
                    _add(name, cat)
        except OSError:
            pass

    # Parse requirements.txt
    reqs = root / "requirements.txt"
    if reqs.exists():
        _add("Python", "language")
        try:
            content = reqs.read_text().lower()
            for dep, (name, cat) in _PYTHON_DEPS.items():
                if dep in content:
                    _add(name, cat)
        except OSError:
            pass

    return detected


def generate_vibeignore(root: Path, detected: list[tuple[str, str]]) -> str:
    """Generate .vibeignore content based on detected stack."""
    lines = list(_BASE_IGNORES)

    fw_names = {name for name, _ in detected}
    for fw_name, fw_ignores in _FRAMEWORK_IGNORES.items():
        if fw_name in fw_names:
            lines.extend(fw_ignores)

    return "\n".join(lines) + "\n"


def run_init(path: str = ".") -> str:
    """Run the init command. Returns formatted output."""
    root = Path(path).resolve()

    if not root.exists():
        return f"Error: path not found: {root}"

    lines = []
    lines.append("")
    lines.append("  Detecting project stack...")
    lines.append("")

    detected = detect_stack(root)

    if not detected:
        lines.append("  No frameworks detected. Generating base .vibeignore.")
    else:
        # Group by category
        by_cat: dict[str, list[str]] = {}
        for name, cat in detected:
            by_cat.setdefault(cat, []).append(name)

        for cat, names in by_cat.items():
            lines.append(f"  {cat:12s}  {', '.join(names)}")

    lines.append("")

    # Write .vibeignore
    ignore_path = root / ".vibeignore"
    content = generate_vibeignore(root, detected)

    if ignore_path.exists():
        lines.append(f"  .vibeignore already exists — skipped (delete it first to regenerate)")
    else:
        ignore_path.write_text(content)
        lines.append(f"  Created .vibeignore ({len(content.splitlines())} rules)")

    # Relevant checks
    fw_names = {name for name, _ in detected}
    relevant_checks = []
    if fw_names & {"Supabase"}:
        relevant_checks.append("supabase (RLS, service_role key, anon key)")
    if fw_names & {"Firebase"}:
        relevant_checks.append("firebase (open security rules, API keys)")
    if fw_names & {"Next.js", "Nuxt", "Vercel"}:
        relevant_checks.append("nextjs (NEXT_PUBLIC_ secrets, API route auth)")
    if fw_names & {"NextAuth", "Auth.js", "Clerk"}:
        relevant_checks.append("nextauth (missing secret, trustHost)")
    if fw_names & {"Prisma", "Drizzle"}:
        relevant_checks.append("prisma (raw queries, SQL injection)")
    if fw_names & {"Stripe"}:
        relevant_checks.append("stripe (webhook verification, key exposure)")
    if fw_names & {"FastAPI", "Django", "Flask", "Express"}:
        relevant_checks.append("injection (SQL, command injection, eval)")

    if relevant_checks:
        lines.append("")
        lines.append("  Checks enabled for your stack:")
        for c in relevant_checks:
            lines.append(f"    + {c}")

    lines.append("")
    lines.append("  Run: vibecheck scan .")
    lines.append("")

    return "\n".join(lines)
